import { expect, test } from '@playwright/test';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { randomUUID } from 'node:crypto';
import { assertLocalTestDatabase } from './helpers/local-test-database';
assertLocalTestDatabase();
const db=new PrismaClient();
test('public share → anonymous contact → native reply → inline signup → calendar, with no lost messages',async({page,request,browser})=>{
 const ids:string[]=[];const suffix=randomUUID().slice(0,8),username=`share_e2e_${suffix}`;
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try {
 const owner=await db.user.create({data:{username,hashedPassword:await bcrypt.hash('LocalShare123!',12),nickname:'Alex',verifiedStudent:true,school:'TUM',onboardingComplete:true}});ids.push(owner.id);
 const startAt=new Date(Date.now()+86400000).toISOString(),endAt=new Date(Date.now()+90000000).toISOString();
 const intent=await db.weeklyIntent.create({data:{userId:owner.id,topic:'COFFEE',activityText:'Coffee after class',note:'Let’s catch up.',timeWindows:[{startAt,endAt}],timePreference:{kind:'EXACT'},exploreVisible:true,expiresAt:new Date(endAt)}});
 const login=await request.post('/api/v1/auth/login',{data:{identifier:username,password:'LocalShare123!',device:{id:`share-${suffix}`,name:'Share test',appVersion:'1.0.0',platformVersion:'17.0'}}});expect(login.status()).toBe(200);
 const headers={Authorization:`Bearer ${(await login.json()).data.tokens.accessToken}`};
 const share=await request.post(`/api/v1/me/weekly-intents/${intent.id}/share`,{headers});expect(share.status()).toBe(200);
 const link=new URL((await share.json()).data.url);const token=link.pathname.split('/').at(-1)!;
 const count=await db.user.count();
 await page.goto(`${link.pathname}?lang=zh-CN`);
 await expect(page.getByRole('heading',{name:'Coffee after class'})).toBeVisible();
 await expect.poll(()=>db.user.count()).toBe(count);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'docs/qa/evidence/2026-10-02-intent-share/public-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'联系我',exact:true}).click();
 const field=page.getByRole('textbox',{name:'打个招呼，或聊聊想约的时间…'});
 await expect(field).toBeVisible();await field.fill('Hi! Can we meet tomorrow?');await page.getByRole('button',{name:'发送',exact:true}).click();
 await expect(page.getByText('招呼已送达，对方回复后会显示在这里。')).toBeVisible();
 const intro=await db.mutualOpportunityMessageRequest.findFirstOrThrow({where:{opportunity:{intentAId:intent.id}}});ids.push(intro.senderId);
 const guestCalendar=await page.request.post('/api/v1/calendar/events',{data:{title:'Bypass',startAt,endAt},headers:{'Idempotency-Key':randomUUID()}});expect(guestCalendar.status()).toBe(401);
 const outsider=await browser.newContext();const outsiderPage=await outsider.newPage();await outsiderPage.goto(`${link.origin}${link.pathname}`);
 expect((await outsiderPage.request.get(`/api/public/intent-share/${token}`)).status()).toBe(200);
 expect((await (await outsiderPage.request.get(`/api/public/intent-share/${token}`)).json()).data.messages).toEqual([]);await outsider.close();
 const reply=await request.post(`/api/v1/me/mutual-opportunities/${intro.opportunityId}/interaction`,{headers:{...headers,'Idempotency-Key':randomUUID()},data:{action:'REPLY',body:'Yes, see you tomorrow!'}});expect(reply.status()).toBe(200);
 await expect(page.getByText('Yes, see you tomorrow!',{exact:true})).toBeVisible();
 await field.fill('Great, thank you!');await page.getByRole('button',{name:'发送',exact:true}).click();await expect(page.getByText('Great, thank you!',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'添加到我的日程',exact:true}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByLabel('用户名',{exact:true}).fill(`joined_${suffix}`);await page.getByLabel('设置密码 · 至少 8 位').fill('LocalShare123!');
 await page.screenshot({path:'docs/qa/evidence/2026-10-02-intent-share/quick-register.png',fullPage:true});
 await page.getByRole('dialog').getByRole('button',{name:'注册并继续',exact:true}).click();
 await expect(page.getByText('仅保存到你自己的日程，具体安排还需和对方确认。',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'保存到我的日程',exact:true}).click();
 await expect(page.getByText('已保存到你的 SideSeat 日程。',{exact:true})).toBeVisible();
 await page.reload();await expect(page.getByText('Yes, see you tomorrow!',{exact:true})).toBeVisible();
 const upgraded=await db.user.findUniqueOrThrow({where:{id:intro.senderId}});expect(upgraded.isGuest).toBe(false);expect(upgraded.username).toBe(`joined_${suffix}`);
 expect(await db.calendarEntry.count({where:{userId:intro.senderId,title:'Coffee after class'}})).toBe(1);
 const nativeLogin=await request.post('/api/v1/auth/login',{data:{identifier:`joined_${suffix}`,password:'LocalShare123!',device:{id:`joined-${suffix}`,name:'New device',appVersion:'1.0.0',platformVersion:'17.0'}}});expect(nativeLogin.status()).toBe(200);expect((await nativeLogin.json()).data.user.id).toBe(intro.senderId);
 await page.screenshot({path:'docs/qa/evidence/2026-10-02-intent-share/registered-chat.png',fullPage:true});expect(errors).toEqual([]);
 const revoke=await request.delete(`/api/v1/me/weekly-intents/${intent.id}/share`,{headers});expect(revoke.status()).toBe(200);
 await page.reload();await expect(page.getByText('这份邀约已经结束或停止分享。')).toBeVisible();
 } finally {await db.user.deleteMany({where:{id:{in:ids}}});await db.$disconnect();}
});
