ALTER TYPE "MessageType" ADD VALUE 'IMAGE';
ALTER TYPE "MessageType" ADD VALUE 'LOCATION';

ALTER TABLE "Message" ADD COLUMN "imageUrl" TEXT,
ADD COLUMN "locationLat" DOUBLE PRECISION,
ADD COLUMN "locationLng" DOUBLE PRECISION,
ADD COLUMN "locationName" TEXT;
