export const shareCopy = {
  en: {
    accountReady: 'Your account is ready', accountReadyHint: 'You can use this account on the web and in SideSeat.', conversationSaved: 'Your conversation is saved.',
    continueInApp: 'Continue in the app', continueWeb: 'Stay on the web',
    appLoginHint: 'Sign in to the app with this account and your new password.',
    appNotOpened: 'App didn’t open?', appBrowserHint: 'Try your browser, or open SideSeat and sign in directly.',
    appInstallHint: 'Not installed? Ask the person who shared this link for access. You can keep chatting here.', installApp: 'Get SideSeat for iPhone',
    usernameChecking: 'Checking username…', usernameAvailable: 'This username is available.', usernameTaken: 'This username is taken. Try another.', usernameCheckFailed: 'Couldn’t check right now. Try again or continue to verify.',
    usernameRules: { tooShort: 'Use at least 2 characters.', tooLong: 'Use at most 32 characters.', invalid: 'Use only letters, numbers, underscores, and hyphens.', reserved: 'This username is reserved.' },
    timeChanged: 'This time changed or expired. Choose again; your message has been kept.',
    intentionClosed: 'This intention has ended. Your existing conversation and plans are still here.',
    live: 'Messages update automatically', reconnecting: 'Reconnecting…', newMessages: 'New messages',
    planInvitation: 'Plan invitation', planPending: 'Awaiting your reply', planConfirmed: 'Confirmed', planDeclined: 'Declined', planCanceled: 'Canceled', planCountered: 'Time changed', planExpired: 'Expired',
    registerAccept: 'Create account & accept invitation', acceptPlan: 'Accept & add to schedule',
    planSignupHint: 'Register to accept and add this plan to both schedules.',
    planAcceptHint: 'Adds this plan to both schedules.', planAccepted: 'Invitation accepted. Added to both schedules.',
    planChanged: 'This invitation has changed. Check its latest status in the conversation.',
    appContinueHint: 'Sign in to the app with this account to keep chatting and view your schedule.',
    invitation: 'An invitation to spend time together', availability: 'Available times', flexible: 'Flexible', undecided: 'Let’s decide together',
    contact: 'Contact me', noAccount: 'No signup needed',
    chat: 'Your conversation', hello: 'Say hello or suggest a time…', send: 'Send', sending: 'Sending…',
    waiting: 'Your greeting is sent. Their reply will appear here.', guest: 'Guest chat · Keep this page to see replies.',
    save: 'Keep in touch', benefits: 'Save your conversation and plans with an account.',
    register: 'Create account & continue', username: 'Username', password: 'Password · at least 8 characters', later: 'Not now',
    saved: 'Account ready. Your conversation is saved.', busy: 'One moment…', error: 'Couldn’t connect. Please try again.',
    owner: 'This is your shared page. New greetings arrive in your app inbox.',
    terms: 'Read how we handle your account and conversation in our Privacy Policy.', close: 'Close', copied: 'Link copied', copy: 'Copy link',
    registered: 'Signed in as', any: 'Any time', morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening',
    plan: 'A plan was shared. Open SideSeat to view and respond.', open: 'Open SideSeat', unavailable: 'This invitation is no longer available.',
    days: 'Choose any of these times to start a conversation.', selectTime: 'Select this time', pendingTime: 'Time to discuss',
  },
  'zh-CN': {
    accountReady: '注册成功', accountReadyHint: '这个账号可以在网页和 SideSeat App 中使用。', conversationSaved: '对话已保存。',
    continueInApp: '在 App 中继续', continueWeb: '留在网页',
    appLoginHint: '用此账号和刚设置的密码登录 App。',
    appNotOpened: 'App 没有打开？', appBrowserHint: '请在浏览器中重试，或直接打开 SideSeat 登录。',
    appInstallHint: '还没安装？向分享者获取安装方式，也可继续在这里聊。', installApp: '安装 SideSeat iPhone 版',
    usernameChecking: '正在检查用户名…', usernameAvailable: '这个用户名可以使用', usernameTaken: '这个用户名已被使用，请换一个', usernameCheckFailed: '暂时无法检查，可重试或继续提交验证',
    usernameRules: { tooShort: '用户名至少需要 2 位', tooLong: '用户名最多 32 位', invalid: '仅支持英文字母、数字、下划线和连字符', reserved: '这个用户名为系统保留，请换一个' },
    timeChanged: '时间已变更或过期，请重新选择；你写的消息已保留。',
    intentionClosed: '这份意愿已结束，你们的对话和计划仍然保留。',
    live: '消息自动更新', reconnecting: '正在重新连接…', newMessages: '查看新消息',
    planInvitation: '计划邀请', planPending: '等待你回复', planConfirmed: '已确认', planDeclined: '已婉拒', planCanceled: '已取消', planCountered: '已提议新时间', planExpired: '已过期',
    registerAccept: '注册并接受邀请', acceptPlan: '接受邀请并加入日程',
    planSignupHint: '注册并接受后，计划加入双方日程。',
    planAcceptHint: '确认后加入双方日程。', planAccepted: '已接受邀请，已加入双方日程。',
    planChanged: '这份邀请已有变化，请查看对话中的最新状态。',
    appContinueHint: '用这个账号登录 App，即可继续聊天、查看日程。',
    invitation: '找个时间，一起做点什么', availability: '我有空的时间', flexible: '时间灵活', undecided: '时间可以一起商量',
    contact: '联系我', noAccount: '无需注册',
    chat: '你们的对话', hello: '打个招呼，或聊聊想约的时间…', send: '发送', sending: '发送中…',
    waiting: '招呼已送达，对方回复后会显示在这里。', guest: '临时对话 · 保留此页查看回复',
    save: '保持联络', benefits: '注册后保留对话和计划。',
    register: '注册并继续', username: '用户名', password: '设置密码 · 至少 8 位', later: '先继续聊',
    saved: '注册完成，对话已保留。', busy: '稍等一下…', error: '暂时连接不上，请再试一次。',
    owner: '这是你的分享页面。收到的新招呼会出现在 App 消息中。',
    terms: '账户及聊天记录的使用说明见隐私政策。', close: '关闭', copied: '链接已复制', copy: '复制链接',
    registered: '当前账号', any: '不限时段', morning: '上午', afternoon: '下午', evening: '晚上',
    plan: '对方分享了一个计划，请在 SideSeat 中查看并回复。', open: '打开 SideSeat', unavailable: '这份邀约已经结束或停止分享。',
    days: '选一个时间，聊聊怎么约。', selectTime: '选择这个时间', pendingTime: '时间待商量',
  },
  de: {
    accountReady: 'Dein Konto ist bereit', accountReadyHint: 'Du kannst dieses Konto im Browser und in SideSeat verwenden.', conversationSaved: 'Dein Gespräch ist gespeichert.',
    continueInApp: 'In der App fortsetzen', continueWeb: 'Im Browser bleiben',
    appLoginHint: 'Melde dich in der App mit diesem Konto und deinem neuen Passwort an.',
    appNotOpened: 'Die App öffnet sich nicht?', appBrowserHint: 'Versuche es im Browser oder öffne SideSeat und melde dich direkt an.',
    appInstallHint: 'Noch nicht installiert? Frage die Person, die den Link geteilt hat, nach Zugang. Du kannst hier weiter chatten.', installApp: 'SideSeat für iPhone installieren',
    usernameChecking: 'Benutzername wird geprüft…', usernameAvailable: 'Dieser Benutzername ist verfügbar.', usernameTaken: 'Dieser Benutzername ist vergeben. Wähle einen anderen.', usernameCheckFailed: 'Prüfung derzeit nicht möglich. Versuche es erneut oder fahre zur Prüfung fort.',
    usernameRules: { tooShort: 'Mindestens 2 Zeichen.', tooLong: 'Höchstens 32 Zeichen.', invalid: 'Nur Buchstaben, Zahlen, Unterstriche und Bindestriche verwenden.', reserved: 'Dieser Benutzername ist reserviert.' },
    timeChanged: 'Diese Zeit wurde geändert oder ist vorbei. Bitte erneut wählen; deine Nachricht bleibt erhalten.',
    intentionClosed: 'Dieser Wunsch ist beendet. Euer Gespräch und eure Pläne bleiben erhalten.',
    live: 'Nachrichten werden automatisch aktualisiert', reconnecting: 'Verbindung wird wiederhergestellt…', newMessages: 'Neue Nachrichten',
    planInvitation: 'Planeinladung', planPending: 'Deine Antwort steht aus', planConfirmed: 'Bestätigt', planDeclined: 'Abgelehnt', planCanceled: 'Abgesagt', planCountered: 'Neue Zeit vorgeschlagen', planExpired: 'Abgelaufen',
    registerAccept: 'Konto erstellen & Einladung annehmen', acceptPlan: 'Annehmen & im Kalender speichern',
    planSignupHint: 'Registriere dich und bestätige den Plan für beide Kalender.',
    planAcceptHint: 'Wird in beiden Kalendern gespeichert.', planAccepted: 'Einladung angenommen. In beiden Kalendern gespeichert.',
    planChanged: 'Diese Einladung hat sich geändert. Prüfe den aktuellen Status im Gespräch.',
    appContinueHint: 'Melde dich mit diesem Konto in der App an, um weiterzuschreiben und deinen Kalender zu sehen.',
    invitation: 'Zeit für etwas Gemeinsames', availability: 'Freie Zeiten', flexible: 'Flexibel', undecided: 'Die Zeit besprechen wir zusammen',
    contact: 'Kontakt aufnehmen', noAccount: 'Ohne Registrierung',
    chat: 'Euer Gespräch', hello: 'Sag Hallo oder schlage eine Zeit vor…', send: 'Senden', sending: 'Wird gesendet…',
    waiting: 'Deine Nachricht ist angekommen. Die Antwort erscheint hier.', guest: 'Gastgespräch · Behalte diese Seite für Antworten.',
    save: 'In Kontakt bleiben', benefits: 'Speichere dein Gespräch und deine Pläne mit einem Konto.',
    register: 'Konto erstellen & weiter', username: 'Benutzername', password: 'Passwort · mindestens 8 Zeichen', later: 'Später',
    saved: 'Dein Konto ist bereit. Das Gespräch bleibt erhalten.', busy: 'Einen Moment…', error: 'Keine Verbindung. Bitte versuche es erneut.',
    owner: 'Das ist deine geteilte Seite. Neue Nachrichten erscheinen in deiner App.',
    terms: 'Informationen zu deinem Konto und Gespräch findest du in der Datenschutzerklärung.', close: 'Schließen', copied: 'Link kopiert', copy: 'Link kopieren',
    registered: 'Angemeldet als', any: 'Jederzeit', morning: 'Vormittags', afternoon: 'Nachmittags', evening: 'Abends',
    plan: 'Ein Plan wurde geteilt. Öffne SideSeat, um ihn anzusehen und zu antworten.', open: 'SideSeat öffnen', unavailable: 'Diese Einladung ist nicht mehr verfügbar.',
    days: 'Wähle eine Zeit und kommt ins Gespräch.', selectTime: 'Diese Zeit wählen', pendingTime: 'Zeit noch offen',
  },
};
export type ShareLocale = keyof typeof shareCopy;
