/** Stable codes for `/api/auth/email/send-otp` — map to `authForm.emailOtpErrors` on the client. */
export const EMAIL_OTP_ERROR_CODES = {
  DB_UNAVAILABLE: "EMAIL_OTP_DB_UNAVAILABLE",
  DB_SCHEMA: "EMAIL_OTP_DB_SCHEMA",
  EMAIL_INVALID: "EMAIL_OTP_EMAIL_INVALID",
  EMAIL_ALREADY_REGISTERED: "EMAIL_OTP_EMAIL_ALREADY_REGISTERED",
  RATE_LIMITED: "EMAIL_OTP_RATE_LIMITED",
  EMAIL_NOT_CONFIGURED: "EMAIL_OTP_EMAIL_NOT_CONFIGURED",
  EMAIL_SEND_FAILED: "EMAIL_OTP_EMAIL_SEND_FAILED",
  INVALID_REQUEST: "EMAIL_OTP_INVALID_REQUEST",
  UNKNOWN: "EMAIL_OTP_UNKNOWN",
} as const;

export type EmailOtpErrorCode = (typeof EMAIL_OTP_ERROR_CODES)[keyof typeof EMAIL_OTP_ERROR_CODES];

export const SIGNUP_EMAIL_ERROR_CODES = {
  DB_UNAVAILABLE: "SIGNUP_EMAIL_DB_UNAVAILABLE",
  CODE_INVALID: "SIGNUP_EMAIL_CODE_INVALID",
  EMAIL_ALREADY_REGISTERED: "SIGNUP_EMAIL_EMAIL_ALREADY_REGISTERED",
  USERNAME_TAKEN: "SIGNUP_EMAIL_USERNAME_TAKEN",
  NICKNAME_TAKEN: "SIGNUP_EMAIL_NICKNAME_TAKEN",
  NICKNAME_RESERVED: "SIGNUP_EMAIL_NICKNAME_RESERVED",
  INVALID_REQUEST: "SIGNUP_EMAIL_INVALID_REQUEST",
  UNKNOWN: "SIGNUP_EMAIL_UNKNOWN",
} as const;

export type SignupEmailErrorCode = (typeof SIGNUP_EMAIL_ERROR_CODES)[keyof typeof SIGNUP_EMAIL_ERROR_CODES];
