/** Stable codes for `/api/profile/login-email` — map to `account.loginEmail.errors` on the client. */
export const LOGIN_EMAIL_CHANGE_ERROR_CODES = {
  UNAUTHORIZED: "LOGIN_EMAIL_UNAUTHORIZED",
  DB_UNAVAILABLE: "LOGIN_EMAIL_DB_UNAVAILABLE",
  DB_SCHEMA: "LOGIN_EMAIL_DB_SCHEMA",
  EMAIL_INVALID: "LOGIN_EMAIL_EMAIL_INVALID",
  EMAIL_ALREADY_REGISTERED: "LOGIN_EMAIL_EMAIL_ALREADY_REGISTERED",
  SAME_AS_CURRENT: "LOGIN_EMAIL_SAME_AS_CURRENT",
  CODE_INVALID: "LOGIN_EMAIL_CODE_INVALID",
  INVALID_REQUEST: "LOGIN_EMAIL_INVALID_REQUEST",
  UNKNOWN: "LOGIN_EMAIL_UNKNOWN",
} as const;

export type LoginEmailChangeErrorCode =
  (typeof LOGIN_EMAIL_CHANGE_ERROR_CODES)[keyof typeof LOGIN_EMAIL_CHANGE_ERROR_CODES];
