/** Stable codes for `PATCH /api/profile/password` — map to `account.changePassword.errors` on the client. */
export const PASSWORD_CHANGE_ERROR_CODES = {
  UNAUTHORIZED: "PASSWORD_CHANGE_UNAUTHORIZED",
  DB_UNAVAILABLE: "PASSWORD_CHANGE_DB_UNAVAILABLE",
  DB_SCHEMA: "PASSWORD_CHANGE_DB_SCHEMA",
  CURRENT_INVALID: "PASSWORD_CHANGE_CURRENT_INVALID",
  SAME_AS_CURRENT: "PASSWORD_CHANGE_SAME_AS_CURRENT",
  INVALID_REQUEST: "PASSWORD_CHANGE_INVALID_REQUEST",
  UNKNOWN: "PASSWORD_CHANGE_UNKNOWN",
} as const;

export type PasswordChangeErrorCode =
  (typeof PASSWORD_CHANGE_ERROR_CODES)[keyof typeof PASSWORD_CHANGE_ERROR_CODES];
