export const SIGNUP_ERROR_CODES = {
  DB_UNAVAILABLE: "SIGNUP_DB_UNAVAILABLE",
  USERNAME_TAKEN: "SIGNUP_USERNAME_TAKEN",
  INVALID_REQUEST: "SIGNUP_INVALID_REQUEST",
  UNKNOWN: "SIGNUP_UNKNOWN",
} as const;

export type SignupErrorCode = (typeof SIGNUP_ERROR_CODES)[keyof typeof SIGNUP_ERROR_CODES];
