ALTER TABLE "Connection"
  ADD COLUMN IF NOT EXISTS "readByAAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "readByBAt" TIMESTAMP(3);

ALTER TABLE "UserCourse"
  ADD COLUMN IF NOT EXISTS "courseChatReadAt" TIMESTAMP(3);
